/*
 * This source file was generated by the Gradle 'init' task
 */
package q3;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Input your salary : ");
        double x = sc.nextDouble();
        sc.close();
        if(x <= 15000) {
            x = x * 0.05;
        } else {
            x = 15000 * 0.05;
        }
        System.out.print("Your Welfare is "+ x + " Baht");
    }
}
